test_that("G2k calibration contract freezes a pre-screened 150-seed all-attempt grid", {
  runner <- isdm_dev_path("run-g2k-calibration.R")
  text <- paste(readLines(runner, warn = FALSE), collapse = "\n")
  screen <- isdm_dev_path("g2l-eligible-seeds.R")
  expect_true(file.exists(screen))
  expect_match(text, "g2l_screen_eligible_seeds")
  expect_match(paste(readLines(screen, warn = FALSE), collapse = "\n"), "86201L:87000L")
  expect_match(text, "n_requested = length\\(seeds\\)")
  expect_match(text, "n_missing")
  expect_match(text, "No fit was run")
  profile_runner <- isdm_dev_path("run-g2i-recovery-prerun.R")
  profile_text <- paste(readLines(profile_runner, warn = FALSE), collapse = "\n")
  expect_match(profile_text, "optimized_initial")
  expect_match(profile_text, "retry_convergence")
  expect_match(profile_text, "selected_attempt")
  expect_match(profile_text, "G2I_PRIVATE_R_LIB")
  expect_match(profile_text, "loadNamespace\\(\"gllvmTMB\"")
  fir_wrapper <- isdm_dev_path("run-g2k-calibration-fir.sbatch")
  fir_text <- paste(readLines(fir_wrapper, warn = FALSE), collapse = "\n")
  expect_match(fir_text, "SLURM_ARRAY_TASK_ID \\+ 1")
  expect_match(fir_text, "\\^\\[1-9\\]\\[0-9\\]\\*\\$")
})
